### ISSUE TITLE
Multi-threaded creation of Gutenberg data

### ISSUE THREAD

**Issue by ChillarAnand** [c-w/Gutenberg#20]
looks like it is using only  one core while creating database. multi thread should speed up?

**Comment by c-w** [comment]
Any ideas on how to best implement this?

**Comment by yever** [comment]
This refers to the extraction of the metadata, right? Well, according to [this](http://stackoverflow.com/a/27840223/4696215), extracting files from a tar file one by one is as slow as extracting all the files times the number of files, because the files are not indexed. I guess this means there should be a major improvement in performance if ``extractall`` is used instead of ``extractfile``, though it would consume more disk space.

Having all the files extracted would allow multithreading over them, since the files to be opened won't overlap. Naturally, the extracted files would have to be deleted after iterating over them.

Does this make sense?

**Comment by yever** [comment]
Well, I have tested it and there's no speed improvement. In fact, ``extractall`` was slightly (but not significantly) slower.

**Comment by yever** [comment]
There's no improvement for a single process, but I've managed to use multiprocessing with the method I've proposed (i.e., extracting the files) and it's more than 3 times faster. @c-w - would you accept a pull request for this method?

**Comment by c-w** [comment]
@yever -- yes, please do open a pull request. That would be great.

**Comment by c-w** [comment]
Resolving in favor of #31.
