### ISSUE TITLE
Fuzzy Searches on Author

### ISSUE THREAD

**Issue by chriswait** [c-w/Gutenberg#39]
It seems that at different times in this project's development, fuzzy searches on an author's name have been discussed and were even implemented at one stage (using `WHERE author LIKE` in https://github.com/c-w/Gutenberg/blob/710052ce5cab7ea45b101ab756c7f1b29091236a/gutenberg/corpus.py#L48), so I apologise if this is redundant.

My use case for this project is essentially grabbing the text content of texts written by a given author. Judging by the README, the functionality provided by `get_etexts("author", "Melville, Hermann") is able to provide the file IDs, which can then be easily downloaded.

However, `get_etexts("author", "Melville, Herman")` (i.e dropping the second "n", as the author's name is actually shown at http://www.gutenberg.org/ebooks/author/9) returns an _empty_ frozenset.

Should I assume that this project currently does not support this feature? If not, I'd be happy to contribute, but the current RDF-based implementation isn't something I currently have any experience with.

**Comment by c-w** [comment]
Hi @chriswait. Thanks for getting in touch.

One way to implement fuzzy matching would be to provide an alternative implementation of [MetadataExtractor.get_etexts](https://github.com/c-w/Gutenberg/blob/95910b6bd49a788c8d3f4b94412d0b051f04a847/gutenberg/query/api.py#L85-L91) that uses [Sparql](http://rdflib.readthedocs.org/en/stable/intro_to_sparql.html) instead of [tuple-indexing](https://github.com/c-w/Gutenberg/blob/95910b6bd49a788c8d3f4b94412d0b051f04a847/gutenberg/query/extractors.py#L34-L37) for retrieval.

Let me know what you find out!

**Comment by c-w** [comment]
@chriswait Given that it's been over a year, I'm going to close this issue.

Note that we've recently made querying by author name more like what you'd expect (see #43) which should alleviate the problem you mentioned: querying for "Melville, Herman" now returns the correct results.

**Comment by chriswait** [comment]
@c-w thanks for following this up! It looks like #43 is indeed pretty close to what I wanted at the time.

**Comment by wwymak** [comment]
@c-w I'm hoping to get texts by subject with fuzzy matching rather than knowing the exact matches for subjects... so does your suggestion from two years ago about 
> One way to implement fuzzy matching would be to provide an alternative implementation of MetadataExtractor.get_etexts that uses Sparql instead of tuple-indexing for retrieval.

still applies?

Thanks!

**Comment by c-w** [comment]
@wwymak Yes that suggestion still applies.
